export const taguig_baarangay = [
  "Bagumbayan",
  "Bambang",
  "Calzada",
  "Central Bicutan",
  "Signal Village",
  "Fort Bonifacio",
  "Hagonoy",
  "Ibayo-Tipas",
  "Katuparan",
  "Ligid-Tipas",
  "Lower Bicutan",
  "Maharlika Village",
  "Napindan",
  "New Lower Bicutan",
  "North Daang hari",
  "North Signal Village",
  "Paglingon",
  "Pinagsama",
  "San Miguel",
  "Santa Ana",
  "South Daang Hari",
  "South Signal Village",
  "Tanyag",
  "Tuktukan",
  "Upper Bicutan",
  "Ususan",
  "Wawa",
  "Western Bicutan",
];
