export const gaming = [
  {
    year: 2011,
    mobile: 25,
    pc: 39,
    console: 44,
  },
  {
    year: 2012,
    mobile: 21,
    pc: 37,
    console: 45,
  },
  {
    year: 2013,
    mobile: 23,
    pc: 38,
    console: 39,
  },
  {
    year: 2014,
    mobile: 29,
    pc: 36,
    console: 35,
  },
  {
    year: 2015,
    mobile: 34,
    pc: 34,
    console: 32,
  },
  {
    year: 2016,
    mobile: 40,
    pc: 30,
    console: 30,
  },
  {
    year: 2017,
    mobile: 41,
    pc: 29,
    console: 25,
  },
  {
    year: 2018,
    mobile: 50,
    pc: 30,
    console: 23,
  },
];

export const confidence = [
  {
    year: 2007,
    mobile: 285,  
  },
  {
    year: 2008,
    mobile: 250,  
  },
  {
    year: 2009,
    mobile: 243,  
  },
  {
    year: 2010,
    mobile: 257,  
  }, 
  {
    year: 2011,
    mobile: 219,  
  },
  {
    year: 2012,
    mobile: 216,  
  },
  {
    year: 2013,
    mobile: 205,
  },
  {
    year: 2014,
    mobile: 236,
  },
  {
    year: 2015,
    mobile: 217,
  },
  {
    year: 2016,
    mobile: 209,   
  },
  {
    year: 2017,
    mobile: 219,   
  },
  {
    year: 2018,
    mobile: 276,
  },
];

//
export const bitecase = [
  {
    year: 2007, bites: 176501,  
  },
  {
    year: 2008, bites: 190095,  
  },
  {
    year: 2009, bites: 216569,  
  },
  {
    year: 2010, bites: 328733,  
  }, 
  {
    year: 2011, bites: 410811,  
  },
  {
    year: 2012, bites: 522420,  
  },
  {
    year: 2013, bites: 683302,
  },
  {
    year: 2014, bites: 783302,
  },
  {
    year: 2015, bites: 1403041,
  },
  {
    year: 2016, bites: 1229607,   
  },
  {
    year: 2017, bites: 1156068,   
  },
  {
    year: 2018, bites: 1165822,
  },
];

export const bitcoin = [
  { date: new Date(2015, 10, 15), price: 346 },
  { date: new Date(2015, 11, 17), price: 441 },
  { date: new Date(2016, 0, 16), price: 435 },
  { date: new Date(2016, 1, 21), price: 415 },
  { date: new Date(2016, 3, 25), price: 445 },
  { date: new Date(2016, 4, 29), price: 460 },
  { date: new Date(2016, 5, 20), price: 730 },
  { date: new Date(2016, 7, 5), price: 600 },
  { date: new Date(2016, 8, 14), price: 617 },
  { date: new Date(2016, 9, 30), price: 674 },
  { date: new Date(2016, 11, 21), price: 785 },
  { date: new Date(2017, 0, 8), price: 991 },
  { date: new Date(2017, 1, 9), price: 1028 },
  { date: new Date(2017, 2, 9), price: 1251 },
  { date: new Date(2017, 3, 6), price: 1103 },
  { date: new Date(2017, 4, 4), price: 1392 },
  { date: new Date(2017, 5, 11), price: 2747 },
  { date: new Date(2017, 6, 19), price: 2203 },
  { date: new Date(2017, 7, 18), price: 4114 },
  { date: new Date(2017, 8, 19), price: 3840 },
  { date: new Date(2017, 9, 19), price: 5591 },
  { date: new Date(2017, 10, 14), price: 6716 },
  { date: new Date(2017, 11, 22), price: 17905 },
  { date: new Date(2018, 0, 23), price: 11438 },
  { date: new Date(2018, 1, 10), price: 8125 },
  { date: new Date(2018, 2, 6), price: 11079 },
  { date: new Date(2018, 3, 7), price: 6913 },
  { date: new Date(2018, 4, 9), price: 9511 },
  { date: new Date(2018, 5, 6), price: 7553 },
  { date: new Date(2018, 6, 18), price: 6400 },
];

// Human Rabies Exposures by Region per category, Philippines,2018
export const incidence = [
  {
    year: 1, //region
    cat1: 524, //cat1
    cat2: 62960, //cat2
    cat3: 11845, //cat3
  },
  {
    year: 2,
    cat1: 291,
    cat2: 74652,
    cat3: 17936,
  },
  {
    year: 3,
    cat1: 596,
    cat2: 102746,
    cat3: 25363,
  },
  {
    year: 4.1,
    cat1: 1635,
    cat2: 69894,
    cat3: 20945,
  },
  {
    year: 4.2,
    cat1: 982,
    cat2: 24465,
    cat3: 32,
  },
  {
    year: 5,
    cat1: 868,
    cat2: 32830,
    cat3: 9403,
  },
  {
    year: 6,
    cat1: 131,
    cat2: 50905,
    cat3: 42476,
  },
  {
    year: 7,
    cat1: 1651,
    cat2: 65578,
    cat3: 34936,
  },
  {
    year: 8,
    cat1: 29,
    cat2: 15861,
    cat3: 11551,
  },
  {
    year: 9,
    cat1: 1107,
    cat2: 49928,
    cat3: 14336,
  },
  {
    year: 10,
    cat1: 0,
    cat2: 47218,
    cat3: 11166,
  },
  {
    year: 11,
    cat1: 96,
    cat2: 37896,
    cat3: 6678,
  },
  {
    year: 12,
    cat1: 572,
    cat2: 34840,
    cat3: 12589,
  },
  {
    year: 13, //CARAGA
    cat1: 309,
    cat2: 17549,
    cat3: 4722,
  },
  {
    year: 14, //CAR
    cat1: 655,
    cat2: 20360,
    cat3: 7814,
  },
  {
    year: 15, //NCR
    cat1: 1154,
    cat2: 128125,
    cat3: 58443,
  },
  {
    year: 15, //ARMM
    cat1: 156,
    cat2: 806,
    cat3: 460,
  },
];

export const barangay = [
  { barangay: "Bagumbayan", val: 219 },
  { barangay: "Bangbang", val: 419 },
  { barangay: "Calzada", val: 100 },
  { barangay: "Central Bicutan", val: 348 },
  { barangay: "Central Signal", val: 222 },
  { barangay: "Fort Bonifacio", val: 70 },
  { barangay: "Hagonoy", val: 348 },
  { barangay: "Ibayo Tipas", val: 48 },
  { barangay: "Katuparan", val: 348 },
  { barangay: "Ligid Tipas", val: 33 },
  { barangay: "Lower Bicutan", val: 648 },
  { barangay: "Maharlika", val: 12 },
  { barangay: "Napindan", val: 348 },
  { barangay: "New Lower Bicutan", val: 348 },
  { barangay: "North Daanghari", val: 340 },
  { barangay: "North Signal", val: 348 },
  { barangay: "Palingon Tipas", val: 26 },
  { barangay: "Pinagsama", val: 101 },
  { barangay: "San Miguel", val: 48 },
  { barangay: "Santa Ana", val: 123 },
  { barangay: "South Daanghari", val: 20 },
  { barangay: "South Signal", val: 340 },
  { barangay: "Tanyag", val: 509 },
  { barangay: "Tuktukan", val: 10 },
  { barangay: "Ususan", val: 99 },
  { barangay: "Upper Bicutan", val: 188 },
  { barangay: "Wawa", val: 340 },
  { barangay: "Western Bicutan", val: 516 },
];

export const ageStructure = [
  {
    state: "Germany",
    young: 6.7,
    middle: 28.6,
    older: 5.1,
  },
  {
    state: "Japan",
    young: 9.6,
    middle: 43.4,
    older: 9,
  },
  {
    state: "Russia",
    young: 13.5,
    middle: 49,
    older: 5.8,
  },
  {
    state: "USA",
    young: 30,
    middle: 90.3,
    older: 14.5,
  },
];

export const contributors = [
  {
    login: "kvet",
    id: 929987,
    avatar_url: "https://avatars2.githubusercontent.com/u/929987?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/kvet",
    html_url: "https://github.com/kvet",
    followers_url: "https://api.github.com/users/kvet/followers",
    following_url: "https://api.github.com/users/kvet/following{/other_user}",
    gists_url: "https://api.github.com/users/kvet/gists{/gist_id}",
    starred_url: "https://api.github.com/users/kvet/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/kvet/subscriptions",
    organizations_url: "https://api.github.com/users/kvet/orgs",
    repos_url: "https://api.github.com/users/kvet/repos",
    events_url: "https://api.github.com/users/kvet/events{/privacy}",
    received_events_url: "https://api.github.com/users/kvet/received_events",
    type: "User",
    site_admin: false,
    contributions: 301,
  },
  {
    login: "SergeyAlexeev",
    id: 1897913,
    avatar_url: "https://avatars3.githubusercontent.com/u/1897913?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/SergeyAlexeev",
    html_url: "https://github.com/SergeyAlexeev",
    followers_url: "https://api.github.com/users/SergeyAlexeev/followers",
    following_url:
      "https://api.github.com/users/SergeyAlexeev/following{/other_user}",
    gists_url: "https://api.github.com/users/SergeyAlexeev/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/SergeyAlexeev/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/SergeyAlexeev/subscriptions",
    organizations_url: "https://api.github.com/users/SergeyAlexeev/orgs",
    repos_url: "https://api.github.com/users/SergeyAlexeev/repos",
    events_url: "https://api.github.com/users/SergeyAlexeev/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/SergeyAlexeev/received_events",
    type: "User",
    site_admin: false,
    contributions: 113,
  },
  {
    login: "gsobolev",
    id: 4580098,
    avatar_url: "https://avatars0.githubusercontent.com/u/4580098?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/gsobolev",
    html_url: "https://github.com/gsobolev",
    followers_url: "https://api.github.com/users/gsobolev/followers",
    following_url:
      "https://api.github.com/users/gsobolev/following{/other_user}",
    gists_url: "https://api.github.com/users/gsobolev/gists{/gist_id}",
    starred_url: "https://api.github.com/users/gsobolev/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/gsobolev/subscriptions",
    organizations_url: "https://api.github.com/users/gsobolev/orgs",
    repos_url: "https://api.github.com/users/gsobolev/repos",
    events_url: "https://api.github.com/users/gsobolev/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/gsobolev/received_events",
    type: "User",
    site_admin: false,
    contributions: 70,
  },
  {
    login: "dxbykov",
    id: 8307562,
    avatar_url: "https://avatars2.githubusercontent.com/u/8307562?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dxbykov",
    html_url: "https://github.com/dxbykov",
    followers_url: "https://api.github.com/users/dxbykov/followers",
    following_url:
      "https://api.github.com/users/dxbykov/following{/other_user}",
    gists_url: "https://api.github.com/users/dxbykov/gists{/gist_id}",
    starred_url: "https://api.github.com/users/dxbykov/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/dxbykov/subscriptions",
    organizations_url: "https://api.github.com/users/dxbykov/orgs",
    repos_url: "https://api.github.com/users/dxbykov/repos",
    events_url: "https://api.github.com/users/dxbykov/events{/privacy}",
    received_events_url: "https://api.github.com/users/dxbykov/received_events",
    type: "User",
    site_admin: false,
    contributions: 63,
  },
  {
    login: "MaximKudriavtsev",
    id: 15093892,
    avatar_url: "https://avatars2.githubusercontent.com/u/15093892?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/MaximKudriavtsev",
    html_url: "https://github.com/MaximKudriavtsev",
    followers_url: "https://api.github.com/users/MaximKudriavtsev/followers",
    following_url:
      "https://api.github.com/users/MaximKudriavtsev/following{/other_user}",
    gists_url: "https://api.github.com/users/MaximKudriavtsev/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/MaximKudriavtsev/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/MaximKudriavtsev/subscriptions",
    organizations_url: "https://api.github.com/users/MaximKudriavtsev/orgs",
    repos_url: "https://api.github.com/users/MaximKudriavtsev/repos",
    events_url:
      "https://api.github.com/users/MaximKudriavtsev/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/MaximKudriavtsev/received_events",
    type: "User",
    site_admin: false,
    contributions: 54,
  },
  {
    login: "viterobk",
    id: 15941408,
    avatar_url: "https://avatars3.githubusercontent.com/u/15941408?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/viterobk",
    html_url: "https://github.com/viterobk",
    followers_url: "https://api.github.com/users/viterobk/followers",
    following_url:
      "https://api.github.com/users/viterobk/following{/other_user}",
    gists_url: "https://api.github.com/users/viterobk/gists{/gist_id}",
    starred_url: "https://api.github.com/users/viterobk/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/viterobk/subscriptions",
    organizations_url: "https://api.github.com/users/viterobk/orgs",
    repos_url: "https://api.github.com/users/viterobk/repos",
    events_url: "https://api.github.com/users/viterobk/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/viterobk/received_events",
    type: "User",
    site_admin: false,
    contributions: 27,
  },
  {
    login: "AnnaTikh",
    id: 26564321,
    avatar_url: "https://avatars2.githubusercontent.com/u/26564321?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/AnnaTikh",
    html_url: "https://github.com/AnnaTikh",
    followers_url: "https://api.github.com/users/AnnaTikh/followers",
    following_url:
      "https://api.github.com/users/AnnaTikh/following{/other_user}",
    gists_url: "https://api.github.com/users/AnnaTikh/gists{/gist_id}",
    starred_url: "https://api.github.com/users/AnnaTikh/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/AnnaTikh/subscriptions",
    organizations_url: "https://api.github.com/users/AnnaTikh/orgs",
    repos_url: "https://api.github.com/users/AnnaTikh/repos",
    events_url: "https://api.github.com/users/AnnaTikh/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/AnnaTikh/received_events",
    type: "User",
    site_admin: false,
    contributions: 3,
  },
  {
    login: "oliversturm",
    id: 4730969,
    avatar_url: "https://avatars2.githubusercontent.com/u/4730969?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/oliversturm",
    html_url: "https://github.com/oliversturm",
    followers_url: "https://api.github.com/users/oliversturm/followers",
    following_url:
      "https://api.github.com/users/oliversturm/following{/other_user}",
    gists_url: "https://api.github.com/users/oliversturm/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/oliversturm/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/oliversturm/subscriptions",
    organizations_url: "https://api.github.com/users/oliversturm/orgs",
    repos_url: "https://api.github.com/users/oliversturm/repos",
    events_url: "https://api.github.com/users/oliversturm/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/oliversturm/received_events",
    type: "User",
    site_admin: false,
    contributions: 2,
  },
  {
    login: "alexey-semikozov",
    id: 7069422,
    avatar_url: "https://avatars1.githubusercontent.com/u/7069422?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/alexey-semikozov",
    html_url: "https://github.com/alexey-semikozov",
    followers_url: "https://api.github.com/users/alexey-semikozov/followers",
    following_url:
      "https://api.github.com/users/alexey-semikozov/following{/other_user}",
    gists_url: "https://api.github.com/users/alexey-semikozov/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/alexey-semikozov/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/alexey-semikozov/subscriptions",
    organizations_url: "https://api.github.com/users/alexey-semikozov/orgs",
    repos_url: "https://api.github.com/users/alexey-semikozov/repos",
    events_url:
      "https://api.github.com/users/alexey-semikozov/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/alexey-semikozov/received_events",
    type: "User",
    site_admin: false,
    contributions: 2,
  },
  {
    login: "dirk-pieterse",
    id: 26871970,
    avatar_url: "https://avatars0.githubusercontent.com/u/26871970?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dirk-pieterse",
    html_url: "https://github.com/dirk-pieterse",
    followers_url: "https://api.github.com/users/dirk-pieterse/followers",
    following_url:
      "https://api.github.com/users/dirk-pieterse/following{/other_user}",
    gists_url: "https://api.github.com/users/dirk-pieterse/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/dirk-pieterse/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/dirk-pieterse/subscriptions",
    organizations_url: "https://api.github.com/users/dirk-pieterse/orgs",
    repos_url: "https://api.github.com/users/dirk-pieterse/repos",
    events_url: "https://api.github.com/users/dirk-pieterse/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/dirk-pieterse/received_events",
    type: "User",
    site_admin: false,
    contributions: 1,
  },
  {
    login: "helsus",
    id: 312055,
    avatar_url: "https://avatars1.githubusercontent.com/u/312055?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/helsus",
    html_url: "https://github.com/helsus",
    followers_url: "https://api.github.com/users/helsus/followers",
    following_url: "https://api.github.com/users/helsus/following{/other_user}",
    gists_url: "https://api.github.com/users/helsus/gists{/gist_id}",
    starred_url: "https://api.github.com/users/helsus/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/helsus/subscriptions",
    organizations_url: "https://api.github.com/users/helsus/orgs",
    repos_url: "https://api.github.com/users/helsus/repos",
    events_url: "https://api.github.com/users/helsus/events{/privacy}",
    received_events_url: "https://api.github.com/users/helsus/received_events",
    type: "User",
    site_admin: false,
    contributions: 1,
  },
  {
    login: "psamim",
    id: 1868679,
    avatar_url: "https://avatars3.githubusercontent.com/u/1868679?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/psamim",
    html_url: "https://github.com/psamim",
    followers_url: "https://api.github.com/users/psamim/followers",
    following_url: "https://api.github.com/users/psamim/following{/other_user}",
    gists_url: "https://api.github.com/users/psamim/gists{/gist_id}",
    starred_url: "https://api.github.com/users/psamim/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/psamim/subscriptions",
    organizations_url: "https://api.github.com/users/psamim/orgs",
    repos_url: "https://api.github.com/users/psamim/repos",
    events_url: "https://api.github.com/users/psamim/events{/privacy}",
    received_events_url: "https://api.github.com/users/psamim/received_events",
    type: "User",
    site_admin: false,
    contributions: 1,
  },
  {
    login: "Krijovnick",
    id: 8238559,
    avatar_url: "https://avatars2.githubusercontent.com/u/8238559?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Krijovnick",
    html_url: "https://github.com/Krijovnick",
    followers_url: "https://api.github.com/users/Krijovnick/followers",
    following_url:
      "https://api.github.com/users/Krijovnick/following{/other_user}",
    gists_url: "https://api.github.com/users/Krijovnick/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Krijovnick/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Krijovnick/subscriptions",
    organizations_url: "https://api.github.com/users/Krijovnick/orgs",
    repos_url: "https://api.github.com/users/Krijovnick/repos",
    events_url: "https://api.github.com/users/Krijovnick/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Krijovnick/received_events",
    type: "User",
    site_admin: false,
    contributions: 1,
  },
  {
    login: "tpisto",
    id: 226244,
    avatar_url: "https://avatars0.githubusercontent.com/u/226244?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/tpisto",
    html_url: "https://github.com/tpisto",
    followers_url: "https://api.github.com/users/tpisto/followers",
    following_url: "https://api.github.com/users/tpisto/following{/other_user}",
    gists_url: "https://api.github.com/users/tpisto/gists{/gist_id}",
    starred_url: "https://api.github.com/users/tpisto/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/tpisto/subscriptions",
    organizations_url: "https://api.github.com/users/tpisto/orgs",
    repos_url: "https://api.github.com/users/tpisto/repos",
    events_url: "https://api.github.com/users/tpisto/events{/privacy}",
    received_events_url: "https://api.github.com/users/tpisto/received_events",
    type: "User",
    site_admin: false,
    contributions: 1,
  },
  {
    login: "gerhat",
    id: 11447903,
    avatar_url: "https://avatars3.githubusercontent.com/u/11447903?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/gerhat",
    html_url: "https://github.com/gerhat",
    followers_url: "https://api.github.com/users/gerhat/followers",
    following_url: "https://api.github.com/users/gerhat/following{/other_user}",
    gists_url: "https://api.github.com/users/gerhat/gists{/gist_id}",
    starred_url: "https://api.github.com/users/gerhat/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/gerhat/subscriptions",
    organizations_url: "https://api.github.com/users/gerhat/orgs",
    repos_url: "https://api.github.com/users/gerhat/repos",
    events_url: "https://api.github.com/users/gerhat/events{/privacy}",
    received_events_url: "https://api.github.com/users/gerhat/received_events",
    type: "User",
    site_admin: false,
    contributions: 1,
  },
  {
    login: "paiboon15721",
    id: 4963061,
    avatar_url: "https://avatars3.githubusercontent.com/u/4963061?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/paiboon15721",
    html_url: "https://github.com/paiboon15721",
    followers_url: "https://api.github.com/users/paiboon15721/followers",
    following_url:
      "https://api.github.com/users/paiboon15721/following{/other_user}",
    gists_url: "https://api.github.com/users/paiboon15721/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/paiboon15721/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/paiboon15721/subscriptions",
    organizations_url: "https://api.github.com/users/paiboon15721/orgs",
    repos_url: "https://api.github.com/users/paiboon15721/repos",
    events_url: "https://api.github.com/users/paiboon15721/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/paiboon15721/received_events",
    type: "User",
    site_admin: false,
    contributions: 1,
  },
];